FROM tchellomello/my-ssl-certs
ENV CA_C=GB CA_ST=England CA_L=London CA_O=VinceyInc CA_OU=testing CA_EMAIL=vince@uk.com CA_DAYS=3650
ENV CERT_C=GB CERT_ST=England CERT_L=London CERT_O=VinceyInc CERT_OU=testing CERT_EMAIL=vincey@uk.com CERT_DAYS=365